arm_name: KINOVA_GEN3_2_RIGHT

KINOVA_GEN3_2_RIGHT:
  STIFFNESS_GAIN_X: 100.0
  STIFFNESS_GAIN_Y: 20.0
  STIFFNESS_GAIN_Z: 20.0
  DAMPING_GAIN_X: 0.7
  DAMPING_GAIN_Y: 0.7
  DAMPING_GAIN_Z: 0.7
  STIFFNESS_GAIN_ROLL: 20.0
  STIFFNESS_GAIN_PITCH: 20.0
  STIFFNESS_GAIN_YAW: 20.0